last-train -P30 -q 4 -a 3 -b 3 -r 2 -X 1 -Q1 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta.mydb trial_0_all.fastq > reads.train
lastal -P30 -T1 -q 4 -a 3 -b 3 -r 2 -X 1 -p reads.train /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta.mydb trial_0_all.fastq > trial_0.last.maf 
last-train -P30 -q 4 -a 3 -b 3 -r 2 -X 1 -Q1 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta.mydb trial_6_all.fastq > reads.train
lastal -P30 -T1 -q 4 -a 3 -b 3 -r 2 -X 1 -p reads.train /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta.mydb trial_6_all.fastq > trial_6.last.maf 
last-train -P30 -q 4 -a 3 -b 3 -r 2 -X 1 -Q1 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta.mydb trial_12_all.fastq > reads.train
lastal -P30 -T1 -q 4 -a 3 -b 3 -r 2 -X 1 -p reads.train /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta.mydb trial_12_all.fastq > trial_12.last.maf 
maf-convert sam trial_12.last.maf > trial_12.last.sam
maf-convert sam trial_6.last.maf > trial_6.last.sam
maf-convert sam trial_0.last.maf > trial_0.last.sam
strobealign -t 30 -B 6 -O 5 -E 3 -A 0 -L 1000 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0_all.fastq > /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.strobealign.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.strobealign.sam
strobealign -t 30 -B 6 -O 5 -E 3 -A 0 -L 1000 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12_all.fastq > /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.strobealign.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.strobealign.sam
strobealign -t 30 -B 6 -O 5 -E 3 -A 0 -L 1000 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6_all.fastq > /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.strobealign.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.strobealign.sam
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106.jar -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.mapper.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.mapper.log 
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106-experimental-kmers.jar --block-length 12 -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.mapper.12mer.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.mapper.12mer.log 
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106-experimental-kmers.jar --block-length 18 -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.mapper.18mer.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.mapper.18mer.log 
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106-experimental-kmers.jar --block-length 24 -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.mapper.24mer.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.mapper.24mer.log 
minimap2 -ax sr -t 30 -B 4 -O 3 -E 3 -A 2 --score-N 1 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta.mmi /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0_all.fastq > /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.minimap.sam 
bwa mem -t 30 -B 4 -O 3 -E 3 -A 2 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0_all.fastq > /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.bwa.sam 
bowtie2 --threads 30 --mp 6,6 --rfg 5,3 --rdg 5,3 --np 1 --ignore-quals -x /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta -U /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0_all.fastq -S /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_0.bowtie.sam
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106.jar -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.mapper.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.mapper.log 
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106-experimental-kmers.jar --block-length 12 -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.mapper.12mer.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.mapper.12mer.log 
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106-experimental-kmers.jar --block-length 18 -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.mapper.18mer.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.mapper.18mer.log 
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106-experimental-kmers.jar --block-length 24 -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.mapper.24mer.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.mapper.24mer.log 
minimap2 -ax sr -t 30 -B 4 -O 3 -E 3 -A 2 --score-N 1 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta.mmi /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12_all.fastq > /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.minimap.sam 
bwa mem -t 30 -B 4 -O 3 -E 3 -A 2 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12_all.fastq > /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.bwa.sam 
bowtie2 --threads 30 --mp 6,6 --rfg 5,3 --rdg 5,3 --np 1 --ignore-quals -x /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta -U /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12_all.fastq -S /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_12.bowtie.sam
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106.jar -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.mapper.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.mapper.log 
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106-experimental-kmers.jar --block-length 12 -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.mapper.12mer.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.mapper.12mer.log 
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106-experimental-kmers.jar --block-length 18 -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.mapper.18mer.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.mapper.18mer.log 
java -Xms25g -Xmx25g -jar /home/caozhichongchong/WS/WS2/scripts/snp_curate/mapper-1.1.0-alpha106-experimental-kmers.jar --block-length 24 -vv --no-infer-ancestors --additional-extend-insertion-penalty 0 --max-penalty 0.60 --snp-penalty 6 --new-indel-penalty 5 --extend-indel-penalty 3 --ambiguity-penalty 1 --num-threads 30 --reference /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta --queries /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6_all.fastq  --out-sam /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.mapper.24mer.sam | tee /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.mapper.24mer.log 
minimap2 -ax sr -t 30 -B 4 -O 3 -E 3 -A 2 --score-N 1 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta.mmi /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6_all.fastq > /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.minimap.sam 
bwa mem -t 30 -B 4 -O 3 -E 3 -A 2 /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6_all.fastq > /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.bwa.sam 
bowtie2 --threads 30 --mp 6,6 --rfg 5,3 --rdg 5,3 --np 1 --ignore-quals -x /media/caozhichongchong/0fca1a13-dd3f-43f5-9b94-876be77c58da/WS1/genome/donor_species/SNP_curate/test_data/penalty_test//am0230.fasta -U /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6_all.fastq -S /home/caozhichongchong/WS/WS2/scripts/snp_curate/SNP_model_penalty/compare_final//trial_6.bowtie.sam
